#!/bin/bash
#
# Install Extra Packages
cd /tmp
curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
unzip rclone-current-linux-amd64.zip
sudo mv rclone-*-linux-amd64/rclone /home/builder/bin/
sudo curl https://raw.githubusercontent.com/fabianonline/telegram.sh/master/telegram -so  /home/builder/bin/telegram
sudo chmod a+x /home/builder/bin/telegram

# Fix TimeZone
sudo ln -snf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# Setup Configs
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
echo "$tg_auth" > ~/.telegram.sh

# Notify In telegram
telegram -M "*juice ROM Compile Status*: \`TRIGGERED!\`.
*Triggered at*:- \`$(date)\`."

# Pull CCache
cd $CCACHE_DIR
rclone copy juice:/ccache/dot_ccache $CCACHE_DIR -P
tar -I "zstd -1 -T2" -xf dot_ccache
rm dot_ccache

# Push CCache
sleep 100m
tar -I "zstd -1 -T2" -cf dot_ccache *
rclone copy dot_ccache juice:/ccache/ -P
