#!/bin/bash
cd $HOME

# Notify In telegram
telegram -M "*juice ROM Compile Status*: \`STARTED!\`.
*Started at*:- \`$(date)\`."

# Setup CCache
ccache -M 20G
ccache -o compression=true
ccache -z

# Run build process
build_start=$(date +"%s")
#
#

source build/envsetup.sh 
lunch nad_juice-userdebug
export USE_CCACHE=1
export CCACHE_EXEC=$(command -v ccache)
export WITH_GAPPS=true 
export DOT_OFFICIAL=true
make bacon -j8
#
#
build_end=$(date +"%s")
echo "$((build_end - build_start))" > ~/.build_time
