#!/bin/bash
#
cd $HOME

# Configure Git
git config --global color.ui true
git config --global user.name aseelps
git config --global user.email aseelpsathar@gmail.com

# Git Haxxx xD
echo "${git_cookies}" > ~/git_hax.sh
bash ~/git_hax.sh && rm ~/git_hax.sh

# Repo init  and sync
repo init -q --no-repo-verify --depth=1 -u repo init -u https://github.com/NusantaraProject-ROM/android_manifest -b -g default,-device,-mips,-darwin,-notdefault

# Start repo sync
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Purge repo
rm -rf .repo

# Pull Device Sources
git clone https://github.com/MiBengal-Development/Device_xiaomi_J --single-branch -b 11 device/xiaomi/juice
git clone https://github.com/I-n-o-k/prebuilt_vendor_juice --single-branch -b 11 vendor/xiaomi/juice
git clone https://github.com/MiBengal-Development/android_kernel_xiaomi_bengal --single-branch -b 11.0 kernel/xiaomi/juice
